import { useState, useEffect } from "react";
import Loader from "../components/Loader";
import Head from "next/head";
import Header from "@/components/Header";
import HeroBanner from "@/components/HeroBanner";

const HomePage = () => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2800);

    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="bg-[rgb(16,16,16)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Adarsh | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      {loading ? (
        <Loader />
      ) : (
        <>
          {/* Header */}
          <Header />

          {/* Hero */}
          <section id="hero" className="snap-center">
            <HeroBanner />
          </section>

          {/* Background Circles */}
          {/* <BackgroundCircles /> */}

          {/* about */}

          {/* skills */}

          {/* projects */}

          {/* Contact */}
        </>
      )}
    </div>
  );
};

export default HomePage;
